<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-09-11 at 03:15:20.
 */
class DaoBaixarParcelaTest extends PHPUnit_Framework_TestCase {

    /**
     * @var DaoBaixarParcela
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new DaoBaixarParcela;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers DaoBaixarParcela::getClassView
     * @todo   Implement testGetClassView().
     */
    public function testGetClassView() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DaoBaixarParcela::executaView
     * @todo   Implement testExecutaView().
     */
    public function testExecutaView() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DaoBaixarParcela::getParcela
     * @todo   Implement testGetParcela().
     */
    public function testGetParcela() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DaoBaixarParcela::gravar
     * @todo   Implement testGravar().
     */
    public function testGravar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
